# This is a basic workflow to help you get started with Actions

name: CI

env:
  SSH_PRIVATE_KEY: ${{ secrets.EC2SSH }}

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          echo $SSH_PRIVATE_KEY > server.pem
          chmod 400 server.pem
          cat server.pem
          ssh -i server.pem ubuntu@ec2-98-84-97-86.compute-1.amazonaws.com
          touch test.txt
          exit



